name: debian-arm64

on:
  push:
  pull_request:

jobs:
  build_arm64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
    - name: build image
      run: docker build -f Dockerfile.cross_arm64 -t hangover-debian-arm64-build .
    - name: get buildfolder
      run: docker run --rm hangover-ubuntu-build tar -C /root/hangover/ -czf - build > build.tar.gz
    - uses: actions/upload-artifact@v1
      with:
        name: buildfolder
        path: build.tar.gz
